### ISSUE TITLE
Update Snowflake Provider version

### ISSUE THREAD

**Issue by stankud** [Snowflake-Labs/terraform-snowflake-storage-integration-aws#5]
Is it possible to update the snowflake provider dependency to version 0.29.0 or higher?

**Comment by DCastile** [comment]
And also reflect the change in ownership to Snowflake-Labs instead of chanzuckerberg/snowflake

**Comment by sfc-gh-pkommini** [comment]
Fixed by #6.

**Comment by sfc-gh-pkommini** [comment]
You can use version `v0.1.0` or blank version to pull the latest one.
